spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  data:
    mongodb:
      host: ds115523.mlab.com
      port: 15523
      username: dictionaryadmin
      password: Dictionary2dmin
      database: dictionary
      options:
        maxWaitTime: 10000
        sslEnabled: false
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
      base-path: /
      path-mapping:
        health: /health
        info: /info
        prometheus: /prometheus
        metrics: /actuator/metrics
  security:
    enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 300ms